using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("InfoZerk")]
[assembly: AssemblyVersionAttribute("0.0.0.81")]
[assembly: AssemblyFileVersionAttribute("0.0.0.81")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.81")]
[assembly: AssemblyTitleAttribute("AutoTest.NET")]
[assembly: AssemblyProductAttribute("AutoTest.NET")]
[assembly: AssemblyDescriptionAttribute("AutoTest.NET is a product of InfoZerk.")]
[assembly: AssemblyTrademarkAttribute("AutoTest.NET - InfoZerk")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010 InfoZerk, - Original author or authors")]

